### ISSUE TITLE
Bump `inferred-types`

### ISSUE THREAD

**Issue by krystof-k** [yankeeinlondon/builder-api#1]
Please bump `inferred-types`, not buildable due to a [bug](https://github.com/inocan-group/brilliant-errors/issues/1) introduced in `brilliant-errors` v0.6.1 dependency.

**Comment by yankeeinlondon** [comment]
Sorry about this @krystof-k ... brilliant-errors had a non-CJS dependency downstream but I have corrected this. One consequence is that the whole stack (aka, builder-api, inferred-types, brilliant-errors) are all exporting only ESM now. This shouldn't really be an issue as ViteJS is very happy with ESM (as is Vitest and I think Jest now too).

Anyway, I've just release `0.5.0` here and will introduce `vite-plugin-md` which uses it in next hour. Let me know if this fixes things for you.

**Comment by krystof-k** [comment]
Awesome, I will try! Yes, `vite-plugin-md` is what interests me :)

**Comment by krystof-k** [comment]
Looks like this helped, however `vite-plugin-md` is still broken due to `happy-wrapper` (yankeeinlondon/happy-wrapper#2).
